# action.yml
name: 'publish-confluence'
description: 'Publish sphinx docs to atlassian confluence cloud'
inputs:
  username:
    description: 'email of user used to access confluence'
    required: true
  apitoken:
    description: 'apitoken to auth with confluence. Obtain one from https://id.atlassian.com/manage/api-tokens'
    required: true
  docsdir:
    description: 'directory in the repo where the docs are located'
    default: ''
  space:
    description: 'Confluence space to publish the docs to'
    default: ''
  parent_page:
    description: 'Confluence page to publish under'
    default: ''
  url:
    description: 'Custom confluence url'
    defalt: 'https://desire2learn.atlassian.net/'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
